#!/usr/bin/env python3
"""Build a reproducible GPLv3 Prism plugin pack and stage the bundled instrument."""

import argparse
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import tarfile
import urllib.request
import zipfile

ROOT = Path(__file__).resolve().parents[1]
JUCE_VERSION = "7.0.12"
JUCE_SHA256 = "94e3b35e1990cd67f59736bb5e1eff1cfd9590b16fea82696f309a8f59452434"


def generate_bank():
    directory = ROOT / "plugins/prism"
    params = json.loads((directory / "parameters.json").read_text())
    bank = json.loads((directory / "factory.json").read_text())
    arps = json.loads((ROOT / "mpclab/prism_arps.json").read_text())
    lines = [
        "// Generated by scripts/build_prism.py; do not edit.",
        "#pragma once",
        "struct ParamSpec {const char* id; const char* label; float lo, hi, initial, step;};",
        "inline constexpr ParamSpec specs[] = {",
    ]
    for p in params:
        lines.append(
            "{"
            + json.dumps(p["id"])
            + ","
            + json.dumps(p["label"])
            + ","
            + ",".join(str(float(p[k])) + "f" for k in ("low", "high", "default", "step"))
            + "},"
        )
    lines += [
        "};",
        "inline constexpr int parameterCount=sizeof(specs)/sizeof(specs[0]);",
    ]
    # MSVC limits each source string literal to 16 KiB. Concatenated small
    # literals preserve the exact JSON without a platform-specific bank.
    for name, payload in (("factoryJSON", bank), ("arpJSON", arps)):
        encoded = json.dumps(payload)
        lines.append(f"inline const char* {name}=")
        lines.extend(
            'R"PRISM(' + encoded[i : i + 4096] + ')PRISM"' for i in range(0, len(encoded), 4096)
        )
        lines.append(";")
    (directory / "src/Bank.h").write_text("\n".join(lines) + "\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path, help="New release directory")
    parser.add_argument("--sdk-cache", type=Path, default=Path.home() / ".cache/anharmonic-plugin")
    parser.add_argument("--jobs", type=int, default=3)
    args = parser.parse_args()
    output = args.output.resolve()
    release = output.parent / (output.name + ".zip")
    if output.exists() or release.exists():
        parser.error("Output directory or archive exists; choose a new path")
    if subprocess.check_output(["git", "status", "--porcelain"], cwd=ROOT, text=True).strip():
        parser.error(
            "Commit source changes before packaging so the included source matches the binary"
        )
    cache = args.sdk_cache.resolve()
    cache.mkdir(parents=True, exist_ok=True)
    archive = cache / f"JUCE-{JUCE_VERSION}.tar.gz"
    if not archive.exists():
        urllib.request.urlretrieve(
            f"https://codeload.github.com/juce-framework/JUCE/tar.gz/refs/tags/{JUCE_VERSION}",
            archive,
        )
    with archive.open("rb") as stream:
        if hashlib.file_digest(stream, "sha256").hexdigest() != JUCE_SHA256:
            raise RuntimeError("JUCE source checksum mismatch")
    # Always extract the verified source archive, rather than trust a modified cache.
    with tarfile.open(archive) as stream:
        stream.extractall(cache, filter="data")
    sdk = cache / f"JUCE-{JUCE_VERSION}"
    generate_bank()
    build = ROOT / ".native/prism"
    subprocess.run(
        [
            "cmake",
            "-S",
            str(ROOT / "plugins/prism"),
            "-B",
            str(build),
            "-DCMAKE_BUILD_TYPE=Release",
            f"-DJUCE_SOURCE_DIR={sdk}",
            "-DCMAKE_POLICY_VERSION_MINIMUM=3.5",
        ],
        check=True,
    )
    subprocess.run(
        ["cmake", "--build", str(build), "--config", "Release", "-j", str(max(1, args.jobs))],
        check=True,
    )
    subprocess.run(
        ["ctest", "--test-dir", str(build), "-C", "Release", "--output-on-failure"], check=True
    )
    output.mkdir(parents=True)
    products = build / "AnharmonicPrism_artefacts/Release"
    for kind in ("VST3", "AU", "Standalone"):
        source = products / kind
        if source.is_dir():
            shutil.copytree(
                source,
                output / kind,
                ignore=shutil.ignore_patterns("*.exp", "*.lib", "*.pdb", "*.ilk"),
            )
    bundled = ROOT / "plugins/bundled"
    bundled.mkdir(parents=True, exist_ok=True)
    for source in (output / "VST3").glob("*.vst3"):
        shutil.copytree(source, bundled / source.name, dirs_exist_ok=True)
    shutil.copy2(ROOT / "LICENSE", output / "LICENSE")
    shutil.copy2(ROOT / "plugins/prism/README.md", output / "README.md")
    # Ship corresponding project source plus the exact framework source archive.
    subprocess.run(
        [
            "git",
            "archive",
            "--format=zip",
            f"--output={output / 'AnharmonicStudio-source.zip'}",
            "HEAD",
        ],
        cwd=ROOT,
        check=True,
    )
    shutil.copy2(archive, output / archive.name)
    shutil.copy2(archive, bundled / archive.name)
    shutil.copy2(output / "AnharmonicStudio-source.zip", bundled / "AnharmonicStudio-source.zip")
    shutil.copy2(ROOT / "plugins/prism/README.md", bundled / "PRISM-README.md")
    sounds = output / "Sounds"
    sounds.mkdir()
    for item in json.loads((ROOT / "plugins/prism/factory.json").read_text()):
        document = {**item, "format": "anharmonic-prism", "version": 1}
        (sounds / (item["name"] + ".prism.json")).write_text(json.dumps(document, indent=2) + "\n")
    manifest = {
        "version": "1.0.0",
        "source_commit": subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True
        ).strip(),
        "juce_version": JUCE_VERSION,
        "juce_sha256": JUCE_SHA256,
        "formats": [kind for kind in ("VST3", "AU", "Standalone") if (output / kind).exists()],
    }
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    with zipfile.ZipFile(release, "w", zipfile.ZIP_DEFLATED) as stream:
        for f in sorted(output.rglob("*")):
            if f.is_file():
                stream.write(f, Path(output.name) / f.relative_to(output))
    with release.open("rb") as stream:
        digest = hashlib.file_digest(stream, "sha256").hexdigest()
    release.with_suffix(".zip.sha256").write_text(f"{digest}  {release.name}\n")
    print(f"Prism pack: {release}\nSHA256: {digest}")


if __name__ == "__main__":
    main()
