#!/usr/bin/env python3
"""Generate website/app/instrument-bank.js from the desktop Native and Prism banks.

The web studio offers exactly the sounds the desktop ships: the Native/Prism
oscillator tones and the 120 layered Prism performances. Orchestral sounds
that need recorded sample files stay desktop-only. Run after changing a bank;
tests/web/instrument-bank.test.cjs fails if the generated file is stale.
"""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "website/app/instrument-bank.js"
NATIVE_FIELDS = (
    "osc1 osc2 osc_mix osc2_octave detune pulse_width sub noise attack decay sustain release "
    "cutoff resonance filter_env drive spread lfo_rate lfo_pitch lfo_filter volume"
).split()


def build():
    factory = json.loads((ROOT / "plugins/prism/factory.json").read_text())
    performances = json.loads((ROOT / "mpclab/prism_performances.json").read_text())
    arps = json.loads((ROOT / "mpclab/prism_arps.json").read_text())
    tones = []
    for item in factory:
        patch = item["patch"]
        if patch.get("sample_source") or patch.get("sample_layer"):
            continue
        tones.append(
            {
                "name": item["name"],
                "category": item["category"],
                "patch": {key: patch[key] for key in NATIVE_FIELDS},
            }
        )
    layered = [
        {
            "name": item["name"],
            "category": item["category"],
            "patch": {key: item["patch"][key] for key in NATIVE_FIELDS},
            **({"arp": item["arp"]} if "arp" in item else {}),
            "effects": item.get("effects", {}),
        }
        for item in performances
    ]
    data = {"tones": tones, "performances": layered, "arps": arps}
    body = json.dumps(data, separators=(",", ":"), sort_keys=True)
    return (
        "/* Generated by scripts/build_web_instruments.py from plugins/prism/factory.json,\n"
        " * mpclab/prism_performances.json and mpclab/prism_arps.json. Do not edit. */\n"
        f"(function (root) {{ 'use strict'; const bank = Object.freeze({body});\n"
        "  if (typeof module !== 'undefined' && module.exports) module.exports = bank;\n"
        "  root.AnharmonicInstrumentBank = bank;\n"
        "})(typeof globalThis !== 'undefined' ? globalThis : this);\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated file is stale")
    args = parser.parse_args()
    text = build()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            raise SystemExit(
                "website/app/instrument-bank.js is stale; run scripts/build_web_instruments.py"
            )
        print("instrument-bank.js is current")
        return
    OUTPUT.write_text(text)
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(text) // 1024} KiB)")


if __name__ == "__main__":
    main()
